apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
  labels:
    app: demo-app
data:
  index.txt: |
    Hello,
    This is a test file that should be
    mounted in the demo-deployment container
  .htaccess: |
    DirectoryIndex index.txt